services:
  postgres:
    image: postgres:15
    container_name: task_manager_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: task_manager_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: task_manager_mailhog
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 8025:8025

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager_server
    restart: always
    ports:
      - "3333:3333"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
  pgadmin_data:
